# Generated by Django 5.1.3 on 2024-11-27 04:00

import django.db.models.deletion
import galleryapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0003_alter_image_description_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='expire_time',
            field=models.DateTimeField(default=galleryapp.models.default_expire_time),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='galleryapp.image'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='share_code',
            field=models.CharField(default='87d11ae84f5d4befac2246586f01a499', max_length=64, unique=True),
        ),
    ]
