# Generated by Django 5.1.3 on 2024-11-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0004_sharelink_password_alter_sharelink_expire_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelink',
            name='image',
        ),
        migrations.AddField(
            model_name='sharelink',
            name='images',
            field=models.ManyToManyField(related_name='share_links', to='galleryapp.image'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='share_code',
            field=models.CharField(default='15c29a0e19d2408d9e7570e81137b53d', max_length=64, unique=True),
        ),
    ]
