# Generated by Django 5.1.3 on 2024-12-17 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0007_rename_file_path_image_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharelink',
            options={'ordering': ['-expire_time', 'created_time']},
        ),
        migrations.AddField(
            model_name='sharelink',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='expire_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='share_code',
            field=models.CharField(default='b30382cca33045a8b6417b7a52bbef53', max_length=64, unique=True),
        ),
    ]
