# Generated by Django 5.1.3 on 2024-12-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0009_alter_sharelink_share_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='share_code',
            field=models.CharField(default='a029de8281994e32b270c839d36dd6d8', max_length=64, unique=True),
        ),
    ]
