# Generated by Django 5.1.3 on 2025-01-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0010_alter_sharelink_share_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='share_code',
            field=models.CharField(default='59c5e6fa83244c68af238d587e2cd567', max_length=64, unique=True),
        ),
    ]
