# Generated by Django 5.1.3 on 2025-01-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0011_alter_sharelink_share_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='share_code',
            field=models.CharField(default='b0e88ce777b543299b1628bca62e4a1a', max_length=64, unique=True),
        ),
    ]
